const mongoose = require('mongoose')

const { Schema } = mongoose

const AirConditionersSchema = new Schema({
    applianceid:{
        type:String,
        required:true
    },
    name:{
        type:String,
        required:true
    },
    appliancetype:{
        type:String,
        required:true
    },
    appliancecate:{
        type:String,
        required:true
    },
    company:{
        type:String
    },
    starRating:{
        type:String
    },
    capacityTons:{
        type:Number
    },
    color:{
        type:String
    },
    coolingcapacity:{
        type:Number
    },
    compressor:{
        type:String
    },
    dehumidification:{
        type:String
    },
    remoteControl:{
        type:String
    },
    antibacteriaFilter:{
        type:String
    },
    dustFilter:{
        type:String
    },
    features:{
        typee:String
    },
    indoordimension:{
        type:String
    },
    indoorwieght:{
        type:Number
    },
    outdimension:{
        type:String
    },
    outwieght:{
        type:Number
    },
    details:{
        type:String
    },
    price:{
        type:Number
    },
    image:{
        type:String
    },
    powerRequirement:{
        type:String
    },
    annualElectricityConsumption:{
        type:Number
    },
    batterytype:{
        type:String
    },
    airflow:{
        type:String
    },
    rating:{
        type:Number
    },
    fieldsection:{
        type:String,
        required:true
    }
})
module.exports = mongoose.model('airconditioners', AirConditionersSchema)