const mongoose=require('mongoose')
const { Schema } = mongoose
const MachineSchema=new  Schema({
    applianceid:{
        type:Number,
        required:true
    },
    name:{
        type:String,
        required:true
    },
    appliancetype:{
        type:String,
        required:true
    },
    appliancecate:{
        type:String,
        required:true
    },
    company:{
        type:String
    },
    image:{
        type:String
    },
    wieght:{
        type:Number,
        required:true
    },
    washingmethod:{
        type:String
    },
    spinspeed:{
        type:Number
    },
    dryercapcity:{
        type:Number
    },
    dryertype:{
        type:String
    },
    waterlevel:{
        type:String
    },
    color:{
        type:String
    },
    heater:{
        type:String
    },
    inverter:{
        type:String
    },
    washcycletime:{
        type:Number
    },
    spincycletime:{
        type:Number
    },
    price:{
        type:Number
    },
    details:{
        type:String
    }
})

module.exports = mongoose.model('machineadd',MachineSchema)